name: asalhapuja
description: "A new Flutter project."
publish_to: 'none' 
version: 2.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  connectivity_plus: ^6.1.3
  crypto: ^3.0.3
  dio: ^5.4.0
  dropdown_search: ^6.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.9
  get: ^4.6.6
  get_storage: ^2.1.1
  go_router: ^14.8.1
  hive: ^2.2.3
  image_picker: ^1.0.7
  intl: ^0.20.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  lottie: ^3.0.0
  path: ^1.8.3
  path_provider: ^2.1.2
  photo_view: ^0.15.0
  pretty_dio_logger: ^1.3.1
  remixicon: ^1.1.0
  retrofit: ^4.1.0
  shimmer: ^3.0.0
  sqflite: ^2.3.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.3
  retrofit_generator: ^9.1.9
  very_good_analysis: ^7.0.0
  json_serializable: ^6.7.1
  change_app_package_name: ^1.1.0
  icons_launcher: ^3.0.1
  package_rename: ^1.9.0


flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/OpenSans/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/

flutter_assets:
  assets_path: assets/
  output_path: lib/data/utils/
  filename: assets.dart

icons_launcher:
  image_path: "assets/images/appLogo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
