name: asalhapuja
description: A new Flutter project.
publish_to: "none"
version: 1.2.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  connectivity_plus: ^4.0.2
  crypto: ^3.0.3
  dio: ^5.3.3
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  flutter_svg: ^2.0.7
  get: ^4.6.6
  get_storage: ^2.1.1
  hive: ^2.2.3
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2
  lottie: ^2.6.0
  path: ^1.8.3
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  remixicon: ^1.0.0
  retrofit: ^4.0.2
  shimmer: ^3.0.0
  sqflite: ^2.3.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.1
  retrofit_generator: ^8.0.0
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  change_app_package_name: ^1.1.0
  icons_launcher: ^2.1.4

flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/OpenSans/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/

flutter_assets:
  assets_path: assets/
  output_path: lib/data/utils/
  filename: assets.dart

icons_launcher:
  image_path: "assets/images/appLogo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
