name: patrol
description: A new Flutter project.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  crypto: ^3.0.2
  dio: ^4.0.6
  dropdown_search: ^5.0.5
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  get: ^4.6.5
  get_storage: ^2.0.3
  hive: ^2.2.3
  image_picker: ^0.8.6+1
  intl: ^0.18.0
  json_annotation: ^4.8.0
  logger: ^1.1.0
  lottie: ^2.2.0
  path: ^1.8.2
  path_provider: ^2.0.12
  retrofit: ^3.3.1
  shimmer: ^2.0.0
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  golden_toolkit: ^0.14.0
  mocktail: ^0.3.0
  retrofit_generator: ^4.2.0
  very_good_analysis: ^4.0.0+1
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
